"use client";
import { ResponsiveContainer, AreaChart, Area, CartesianGrid, XAxis, YAxis, Tooltip, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell } from "recharts";
import { trendData, weeklyData } from "@/lib/mock-data";

const tooltip = { borderRadius: 8, border: "1px solid var(--border)", boxShadow: "var(--shadow-card)", fontSize: 12 };
export function TrendChart({ compact = false }: { compact?: boolean }) { return <div className={compact ? "h-56" : "h-64"}><ResponsiveContainer width="100%" height="100%"><AreaChart data={trendData} margin={{ left: -24, right: 8, top: 10 }}><defs><linearGradient id="trendFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={0.2}/><stop offset="100%" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="day" tickLine={false} axisLine={false} fontSize={11}/><YAxis tickLine={false} axisLine={false} fontSize={11}/><Tooltip contentStyle={tooltip}/><Area type="monotone" dataKey="productivity" stroke="var(--primary)" strokeWidth={2.5} fill="url(#trendFill)"/></AreaChart></ResponsiveContainer></div>; }
export function HabitLineChart() { return <div className="h-64"><ResponsiveContainer><LineChart data={trendData} margin={{ left: -24, right: 8, top: 12 }}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="day" tickLine={false} axisLine={false} fontSize={11}/><YAxis tickLine={false} axisLine={false} fontSize={11}/><Tooltip contentStyle={tooltip}/><Line type="monotone" dataKey="habits" stroke="var(--success)" strokeWidth={2.5} dot={false}/><Line type="monotone" dataKey="productivity" stroke="var(--lavender)" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></div>; }
export function WeeklyBarChart() { return <div className="h-64"><ResponsiveContainer><BarChart data={weeklyData} margin={{ left: -24, right: 8, top: 12 }}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="week" tickLine={false} axisLine={false} fontSize={11}/><YAxis tickLine={false} axisLine={false} fontSize={11}/><Tooltip contentStyle={tooltip}/><Bar dataKey="completed" fill="var(--primary)" radius={[5,5,0,0]} maxBarSize={34}/></BarChart></ResponsiveContainer></div>; }
export function ProductivityLineChart() { return <div className="h-64"><ResponsiveContainer><LineChart data={weeklyData} margin={{ left: -24, right: 8, top: 12 }}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="week" tickLine={false} axisLine={false} fontSize={11}/><YAxis tickLine={false} axisLine={false} fontSize={11}/><Tooltip contentStyle={tooltip}/><Line type="monotone" dataKey="completed" stroke="var(--primary)" strokeWidth={3}/><Line type="monotone" dataKey="previous" stroke="var(--muted-foreground)" strokeWidth={2} strokeDasharray="5 5"/></LineChart></ResponsiveContainer></div>; }
export function TaskPieChart() { const data=[{name:"Completed",value:68},{name:"Incomplete",value:22},{name:"Skipped",value:10}]; return <div className="h-48"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" innerRadius={52} outerRadius={75} paddingAngle={3}>{data.map((item,index)=><Cell key={item.name} fill={["var(--primary)","var(--warning)","var(--lavender)"][index]}/>)}</Pie><Tooltip contentStyle={tooltip}/></PieChart></ResponsiveContainer></div>; }