import { Check } from "lucide-react";
import { cn } from "@/lib/utils";
import { habitCompletions, habits, matrixData, weekDays } from "@/lib/mock-data";

export function WeeklyHabitMatrix() {
  return <div className="overflow-x-auto"><div className="min-w-[680px]"><div className="grid grid-cols-[150px_repeat(7,1fr)_60px] items-center gap-2 border-b border-border pb-3 text-center text-xs font-medium text-muted-foreground"><span className="text-left">Habit</span>{weekDays.map(day=><span key={day}>{day}</span>)}<span>Rate</span></div>{habits.map((habit,row)=>{const completions=habitCompletions[row] ?? [];return <div key={habit.name} className="grid grid-cols-[150px_repeat(7,1fr)_60px] items-center gap-2 border-b border-border/70 py-3 last:border-0"><span className="truncate text-sm font-medium">{habit.name}</span>{weekDays.map((_,col)=>{const done=completions[col] ?? false;return <span key={col} className={cn("mx-auto grid h-7 w-7 place-items-center rounded-md", done ? "bg-success-soft text-success-strong" : "bg-muted text-muted-foreground")} aria-label={done ? "Completed" : "Not completed"}>{done && <Check className="h-3.5 w-3.5"/>}</span>})}<span className="text-right text-xs font-semibold">{Math.round(completions.filter(Boolean).length/7*100)}%</span></div>})}</div></div>;
}

export function MonthlyHabitMatrix() {
  return <div className="overflow-x-auto"><div className="min-w-[960px]"><div className="grid grid-cols-[130px_repeat(30,1fr)] gap-1 border-b border-border pb-2 text-center text-[10px] text-muted-foreground"><span className="text-left font-medium">September</span>{Array.from({length:30},(_,i)=><span key={i}>{i+1}</span>)}</div>{matrixData.map(row=><div key={row.name} className="grid grid-cols-[130px_repeat(30,1fr)] items-center gap-1 border-b border-border/60 py-2 last:border-0"><span className="truncate text-xs font-medium">{row.name}</span>{row.values.map((done,index)=><span key={index} className={cn("mx-auto h-4 w-4 rounded-[4px]",done?"bg-primary":"bg-muted")} title={`${row.name}, September ${index+1}: ${done?"complete":"not complete"}`}/>)}</div>)}</div></div>;
}